 const Cdata = [

     {
        id:1,
        hash1:"Workshop",
        hash2:"100+ Attentes",
        Registration:"Ended",
        cardPoster:'https://media-exp1.licdn.com/dms/image/C4D22AQHEayQLmKCHQg/feedshare-shrink_800/0/1625913142239?e=1634169600&v=beta&t=lWtYdU2ILAcQXxmuce6nUg61hWWSfClCpA-Pjl6JtdA',
        title:'Interview Training: From Hesitation to Perfection ',
        date:" 23 July 2021 - 25 July 2021",
        instImg:"https://media-exp1.licdn.com/dms/image/C5103AQGgVHSS4vsNCw/profile-displayphoto-shrink_200_200/0/1586700938257?e=1637193600&v=beta&t=7ZKK8QgchkQSVk5M8CVIQvUyOzXlHWd2NwUMFJULFrc",
        instName:"Mukesh Mahay",
        insDesc:"Asst Professor, Soft Skills, HR, NPTEL Certified, Lovely Professional University",
        img:"https://picsum.photos/200/300?random=1",
        Edesc:"Student organization club KHOJ: Find ur Real You is going to organize the most skillful event of Interview training to uplift the communication skills among vertos and to grab any opportunity in future without any fear.  Interview Training: From Hesitation to Perfection is a platform for students to develop their communication skill and get the real time exposure of Interview to crack any placements opportunity. This event is planned in a same manner as companies take interview while placements. 22nd July 2021: Session on Interview Placements, tips and tricks 23rd July 2021: Round 1 (Group Discussion)24th July 2021: Round 2 (Telephonic Interview)25th July 2021: Round 3 (HR Interview)",
        Elink:""
    },
     {
        id:1,
        hash1:"Workshop",
        hash2:"1.5K+ Attentes",
        Registration:"Watch Now",
        cardPoster:'https://media-exp1.licdn.com/dms/image/C5622AQHPPEMtyLolJw/feedshare-shrink_2048_1536/0/1624078095922?e=1634169600&v=beta&t=U8wwzUN1UraPBWgV27UG0mf4yjFqDBkVj0rn1CK2AAI',
        title:'Python Live project ',
        date:" 20 June 2021",
        instImg:"https://media-exp1.licdn.com/dms/image/C5603AQH6_k0V_KuPTw/profile-displayphoto-shrink_200_200/0/1627015791998?e=1637193600&v=beta&t=-KzUjQY_mGQPbcvGp8vMS8zBD5N-ADtJ9UCaRnQJ9w0",
        instName:"Shambhavi Gupta",
        insDesc:"Instructor at Udemy | Instructor at upGrad | Video Content Creator at Great Learning | Video Content Creator at GeeksforGeeks | Founder YT channel FUN WITH DATA SCIENCE | python programmer|Data Science Enthusiast",
        img:"https://picsum.photos/200/300?random=1",
        Edesc:"School of computer science and engineering in association with KHOJ: Find ur Real you organizing an informative and learning Live project workshop in python in collaboration with Ms. Shambhavi Gupta Details of the Workshop: This is going to be two days workshop in which you will be able to Building your own Browser in a simplified and fun way. This workshop is going to be wonderful opportunity for students to observe, shape, supremacy and shine.",
        Elink:"https://www.youtube.com/playlist?list=PLemrrzuSdnJBxX5BhoTArBHLE2zad_1CL"
    },
    {
        id:2,
         hash1:"Webinar",
        hash2:"2.5K+ Attendes",
        Registration:"Watch Now",
        cardPoster:"https://media-exp1.licdn.com/dms/image/C4D22AQGIa0CAXlWGrA/feedshare-shrink_800/0/1622009552184?e=1634169600&v=beta&t=t57FGqXEGDphkxYjL4ScRpgnTEOlu6Q71h788Tzatys",
        title:'Cyber Security',
        date:" 31 May 2021",
        instImg:"https://media-exp1.licdn.com/dms/image/D5635AQF4oxT_nQdGfQ/profile-framedphoto-shrink_200_200/0/1631254442682?e=1631541600&v=beta&t=0OBdmOlVgTUckLTIYBd-3T6nO3SKek_1UoF0AvG5--8",
        instName:"Adarsh Kant",
        insDesc:"| Penetration Tester | Ethical Hacker | Cyber Crime Investigator | Bug Hunter | Technical Speaker | Cyber Security Trainer | Cyber Forensics Investigator | Cyber Crime Reporter | Data Science Enthusiast | Digital Marketer | Flutter Dev | Global Talent Awardee 2021 for Inspiring Youth in Cyber Security Expertise | Featured in 50+ Global News Media's |Co-Founder Cyber3ra, Starwin Global Pvt. Ltd.Global Talent Awardee 2021 for Inspiring Youth in Cybersecurity Expertise 🏆India Prime Education Awards 2021 🏆Cyber Security and Cyber Forensics Expert💻Featured in Business Standard, Japan Times, Yahoo News, Dailyhunt, New York Dispatch, Los Angeles Evening Dispatch and 50 other global news media.80+ certifications🏅Certified Ethical Hacker✅Director for Indian Hospitality Leadership Awards 2020🏆Associate Editor at Voice of Indian Hospitality Magazine 📝CTO At Hospitality Ki Pathshala🙌Delivered 50+ Webinars, Sessions, Guest Lectures at Multiple Banks and Institutions🧑‍🎓Want to Collaborate, Just ping me hereadarshknt@gmail.com",
        img:"https://picsum.photos/200/300?random=1",
        Edesc: "One single vulnerability is all an attacker need. The School of Computer Science and Engineering with student organization Khoj is here to provide you with a one - time opportunity to be a part of Cyber Security Webinar. Cyber security is an effective way to deal with the trending data robbery. Thus, we have Adarsh Kant as our instructor to enhance our knowledge in this domain. He is the co-founder of Cyber3ra and is Global Talents Awardee 2021 for Inspiring Youth in Cyber Security Expertise. About the Webinar : Day-1 : ( Elements of Cyber Secur , Common Security Threths Types of  Web , Data Breaches in 12 months , Case Study , Carries in Cyber Security ,  Popular Certificaties , Precautions and Countermeasure Demonstration ) Day 2: ( Practical Guide on Ransomware , Introduction to Ransomware , History of Ransomware , How does Ransomware work , Case Studies• Building up and deploying our own Ransomware with RAAS , Q & A )",
        Elink:"https://www.youtube.com/watch?v=q9QZspfQFnE&t=23s",
    },
    {
        id:3,
         hash1:"Webinar",
        hash2:"1K attendes",
        Registration:"Watch Now",
        cardPoster:'https://media-exp1.licdn.com/dms/image/C4D22AQHJFn4T_a2iHw/feedshare-shrink_800/0/1619232698896?e=1634169600&v=beta&t=q6gypWLhFCcHbziLSzH0swO7-VtrFutIRdIzrzpjm0A',
        title:'Data Science',
        date:" 24 April 2021",
        instImg:"https://media-exp1.licdn.com/dms/image/C5103AQG-tktTHApa9Q/profile-displayphoto-shrink_200_200/0/1577211824179?e=1637193600&v=beta&t=7OCEitAJmrJF7g1n6tMZX0h9D0kSPBXOrtqJWfG1w9w",
        instName:"Arpit Yadev",
        insDesc:"expert of python, Machine learning & Data Analysis. Pursuing PhD in Machine Learning from SVV, Indore.  Awarded with VDGOOD Inspirational Scientist Award in the 7th International Scientist Awards on Engineering, science and Medicine. ",
        img:"https://picsum.photos/200/300?random=1",
        Edesc:"'Data Science : Exploring the Digital Arena ', Data Science is the most important topic of our 21st century specially in CSE. But most of us are not aware about its vast spects and opportunities. So here to guide and give you the right sense of future career option in data science we Khoj community KHOJ Find Ur Real You Lovely Professional University School of Computer Applications, is organising 3 days of free live webinar on it.Khoj Organisation Welcomes our special guest Arpit Yadav sir for conducting this informative webinar. ",
        Elink:"https://www.youtube.com/playlist?list=PLemrrzuSdnJBuG2M1CuqdqOL_oIcrWVUJ",
    },
    
    {
        id:4,
         hash1:"Workshop",
        hash2:"250+ attendes",
        Registration:'Watch Now',
        cardPoster:'https://media-exp1.licdn.com/dms/image/C4D22AQF2iAX-_x9_CA/feedshare-shrink_800/0/1618332205392?e=1634169600&v=beta&t=5PB56W7IKOvkHV-p_S_GCJcV2O8HA3DIKPinybX5lS8',
        title:'MERN Stack Web Development',
        date:" 16 Apr 2021 - 24 Apr 2021",
        instImg:"https://media-exp1.licdn.com/dms/image/C4E03AQH-CbhDtHws0A/profile-displayphoto-shrink_200_200/0/1618500773458?e=1637193600&v=beta&t=hZAhOyOMwuSmKC2FnNSQ5lViVUdUwH03DCd3FUgrArU",
        instName:"Mr. Prateek Mishara ",
        insDesc:" founder & CEO at TechSim+. He has successfully delivered 200+ trainings inengineering colleges, successfully completed 100+ batches (Classroom & Online) and successfully placed 500+ students.",
        img:"https://picsum.photos/200/300?random=1",
        Edesc:"Student origination club KHOJ : find ur real you under the aegis of Division of Student Welfare organizing an informative and learning one week workshop on “Full Stack Web Development: Build your first website with latest technology” under the aegis of Division of Student Welfare, Lovely Professional University.Special Guest: “ Mr. Prateek Mishara “ Topics Discussed:- 1. Transition to Data science and it's opportunity in Industry 2. Transition to Machine learning and it's opportunity in Industry 3. Transition to Deep learning and it's opportunity in Industry Topics to be covered in one week’s: CREATING WEB PAGES WITH HTML,  STYLING WEB PAGES USING CSS,  HANDLING EVENTS IN JAVASCRIPT,  WORK ON NODE.JS AND EXPRESS.JS,  DATABASE INTEGRATION (MONGO DB),  WORKING WITH REACT JS ",
        Elink:"https://www.youtube.com/playlist?list=PLemrrzuSdnJC13Shq7c5n4bNRzSQPVDAJ",
    },
    {
        id:5,
         hash1:"Workshop",
        hash2:"5K+ attendes",
        Registration:'Watch Now',
        cardPoster:'https://media-exp1.licdn.com/dms/image/C4D22AQG_q3R5Cn4cGg/feedshare-shrink_800/0/1617252596347?e=1634169600&v=beta&t=XcECz7BknvEjoRVnqMPy09WHqedrm0EfO8n0IOnpN6c',
        title:'C++ Masterclass: Beginner to Advance',
        date:" 1 Apr 2021 - 20 Apr 2021",
        instImg:"https://media-exp1.licdn.com/dms/image/C4D03AQFkTKkOKxM8-Q/profile-displayphoto-shrink_200_200/0/1611310798005?e=1637193600&v=beta&t=3nlc1NgBmgV6Ca4gmXLJNg6up4aH4aaoP_qxpsnYIZw",
        instName:"Kshitiz Saini",
        insDesc:" GitHub Extern | DevOps Engineer Intern | DevOps enthusiast who loves OpenSource Technologies",
        img:"https://picsum.photos/200/300?random=1",
        Edesc:"Student Organisation “KHOJ” in collaboration with “dotQuestionmark” is organizing fourteen days workshop on “C++ Masterclass” under the aegis of Division of Student Welfare, Lovely Professional University. About Event: C++ programming Masterclass workshop is a platform for students to learn the most important topics of C++ programming. This workshop is totally focused on learning of program and its implementation, how to use conditionals and logic for building applications that generates a different outcome. This workshop will make coding in C++ easy for you and you will realize how easy C++ language is. The ultimate motto of this workshop is to make you a healthy programmer from an absolute beginner ",
        Elink:"https://www.youtube.com/playlist?list=PLT-OS4nBzV7uTK8JgYUzIRERo4ZBIT-z1",
    },
    {
        id:5,
         hash1:"Bootcamp",
        hash2:"1K+ attendes",
        Registration:'Ended',
        cardPoster:'https://media-exp1.licdn.com/dms/image/C4D22AQG2wIGlsiJ-cg/feedshare-shrink_800/0/1611393809908?e=1634169600&v=beta&t=nwwa4eSWHSEelybhOguXwpqAPC02UDDAkkl0kcwLnOk',
        title:'Python Bootcamp',
        date:" 1 Feb 2021 - 3 Feb 2021",
        instImg:"https://media-exp1.licdn.com/dms/image/C5603AQH6_k0V_KuPTw/profile-displayphoto-shrink_200_200/0/1627015791998?e=1637193600&v=beta&t=-KzUjQY_mGQPbcvGp8vMS8zBD5N-ADtJ9UCaRnQJ9w0",
        instName:"Shambhavi Gupta",
        insDesc:"Instructor at Udemy | Instructor at upGrad | Video Content Creator at Great Learning | Video Content Creator at GeeksforGeeks | Founder YT channel FUN WITH DATA SCIENCE | python programmer|Data Science Enthusiast",
        img:"https://picsum.photos/200/300?random=1",
        Edesc:"KHOJ: Find ur Real you organizing an informative and learning Bootcamp in python in collaboration with Ms. Shambhavi Gupta  This is going to be 3 days Bootcamp in which fundamentals of python language will be taught in a simplified and fun way. This Bootcamp is going to be wonderful opportunity for students to observe, shape, supremacy and shine.",
        Elink:"",
    },
   
   



]

export default Cdata;